  const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
  const GET_FULL_MOVIE_DETAILS = "GET_FULL_MOVIE_DETAILS";
  const GET_MOVIE_COLLECTION_TYPES = "GET_MOVIE_COLLECTION_TYPES";
  const GET_MY_LIST_OF_MOVIES_BY_COLLECTION = "GET_MY_LIST_OF_MOVIES_BY_COLLECTION";
  const CREATE_NEW_COLLECTION_BUTTON = "CREATE_NEW_COLLECTION_BUTTON";
  const CREATE_NEW_MOVIE_COLLECTION = "CREATE_NEW_MOVIE_COLLECTION";
  const ADD_MOVIE_TO_COLLECTION = "ADD_MOVIE_TO_COLLECTION";
  const SHOW_FULL_MOVIE_DETAILS = "SHOW_FULL_MOVIE_DETAILS";
  const SHOW_MOVIE_COLLECTION_TYPES = "SHOW_MOVIE_COLLECTION_TYPES";
  const SHOW_MOVIES_BY_COLLECTION = "SHOW_MOVIES_BY_COLLECTION";

  export {
      GET_POPULAR_MOVIES,
      GET_FULL_MOVIE_DETAILS,
      GET_MOVIE_COLLECTION_TYPES,
      GET_MY_LIST_OF_MOVIES_BY_COLLECTION,
      CREATE_NEW_COLLECTION_BUTTON,
      CREATE_NEW_MOVIE_COLLECTION,
      ADD_MOVIE_TO_COLLECTION,
      SHOW_FULL_MOVIE_DETAILS,
      SHOW_MOVIE_COLLECTION_TYPES,
      SHOW_MOVIES_BY_COLLECTION
  };
