  const SHOW_POPULAR_MOVIES = "SHOW_POPULAR_MOVIES";
  const SHOW_FULL_MOVIE_DETAILS = "SHOW_FULL_MOVIE_DETAILS";
  const SHOW_MOVIE_COLLECTION_TYPES = "SHOW_MOVIE_COLLECTION_TYPES";
  const SHOW_MOVIES_BY_COLLECTION = "SHOW_MY_LIST_OF_MOVIES_BY_COLLECTION";
  const ADD_MOVIE_TO_COLLECTION = "ADD_MOVIE_TO_COLLECTION";
  const DELETE_MOVIE_FROM_COLLECTION = "DELETE_MOVIE_FROM_COLLECTION";
  const SHOW_SEARCH_MOVIE_RESULTS = "SHOW_SEARCH_MOVIE_RESULTS";

  export {
    SHOW_POPULAR_MOVIES,
    SHOW_FULL_MOVIE_DETAILS,
    SHOW_MOVIE_COLLECTION_TYPES,
    SHOW_MOVIES_BY_COLLECTION,
    ADD_MOVIE_TO_COLLECTION,
    DELETE_MOVIE_FROM_COLLECTION,
    SHOW_SEARCH_MOVIE_RESULTS
  };
